---
name: Deploy

on:
  push:
    branches: ["master"]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: "actions/checkout@v4"

      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.*"

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: "Install dependencies"
        run: |
          python -VV
          python -m pip install --upgrade pip
          python -m pip install pipenv
          npm install -g serverless
          cd api
          npm install

      - name: "Deploy stable"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        run: |
          cd api
          pipenv update
          bin/deploy stable

      - name: "Deploy main"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
        run: |
          cd api
          pipenv install git+https://github.com/psf/black.git#egg=black
          bin/deploy main
